<?php 
/**
 * Outputs a list of PDF archives
 * 
 * @param array (if there are archives this is an array of post objects)
 * @param boolean (if there are no archives)
 */
if ( $archives ) : ?>

  <ul class="mb0">
    <?php foreach ( $archives as $archive ) : ?>
      <?php
      $local_file = get_field('autogenerated_pdf_file', $archive->ID);
      
      if ( defined('WP_DEBUG') && defined('LC_ARCHIVE_PDF_PATH') ) {
        $parsed = parse_url($local_file);
        $url = LC_ARCHIVE_PDF_PATH . $parsed['path'];
      } else {
        $url = $local_file;
      }
      ?>
      <li>
        <a href="<?= esc_url($url); ?>" target="_blank">
          <?= Archives\get_archived_post_nicename($archive->ID); ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

<?php else : ?>
  <small class="db"><em>No archives found</em></small>
<?php endif; ?>